config/routes.rb
Rails.application.routes.draw do
  resources :projects
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to project_url(@project), notice: "Project was successfully created."
    else
      render :form_update, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    if @project.update(project_params)
      redirect_to project_url(@project), notice: "Project was successfully updated."
    else
      render :form_update, status: :unprocessable_entity
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BootstrapModal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>
  <body>
    <%= turbo_frame_tag "modal", target: "_top" %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_modal.html.erb
<%
  closable ||= false
  fade_in ||= false
%>
<%= turbo_frame_tag "modal" do %>
  <div class="modal <%= fade_in ? "fade" : ""%>" tabindex="-1" data-controller="modal" id="<%= closable ? "closable" : ""%>">
    <div class="modal-dialog modal-dialog-centered modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <div class= "modal-title fs-3">
            <%= title %>
          </div>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body" id="remote_modal_body" >
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :name, style: "display: block", class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :description, style: "display: block", class: "form-label" %>
    <%= form.text_field :description, class: "form-control" %>
  </div>
  <div class="row mt-2">
    <div class="col text-end">
      <%= form.submit "Save", class:"btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

</div>

app/views/projects/edit.html.erb
<%= render 'partials/modal', title: "Edit Project", fade_in: true do %>
  <%= render "form", project: @project %>
<% end %>

app/views/projects/form_update.turbo_stream.erb
<%= turbo_stream.update "remote_modal_body" do %>
  <%= render "form", project: @project %>
<% end %>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path, data: { turbo: true, turbo_frame: 'modal' } %>

app/views/projects/new.html.erb
<%= render 'partials/modal', title: "New Project", fade_in: true do %>
  <%= render "form", project: @project %>
<% end %>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @project %>
<div>
  <%= link_to "Edit this project", edit_project_path(@project), data: {turbo: true, turbo_frame: "modal"} %> |
  <%= link_to "Back to projects", projects_path %>
  <%= button_to "Destroy this project", @project, method: :delete %>
</div>